# Devoir 3 pour IFT6390 - Fondements de l'apprentissage machine

### Par Olivier Malenfant-Thuot
Matricule: 1012818

## Question 1 - Theoretical Part: Derivatives and relationships between basic functions

### 1.

\begin{equation}
\frac{1}{2}(\tanh(x/2)+1) = \frac{1}{2}(\frac{e^{x/2}-e^{-x/2}}{e^{x/2}+e^{-x/2}}+1) = 
\frac{1}{2}(\frac{e^{x/2}-e^{-x/2}}{e^{x/2}+e^{-x/2}}+\frac{e^{x/2}+e^{-x/2}}{e^{x/2}+e^{-x/2}}) = \frac{1}{2}(\frac{2e^{x/2}}{e^{x/2}+e^{-x/2}}) = \frac{2e^{x/2}(e^{x/2}+e^{-x/2})}{(e^{x/2}+e^{-x/2})^2} = \frac{e^x+1}{e^x+2+e^{-x}} \times \frac{(e^x+1)^{-1}}{(e^x+1)^{-1}} = \frac{1}{1+e^{-x}} = \text{sigmoid}(x)
\end{equation}

### 2.

\begin{equation}
\ln(\text{sigmoid}(x)) = \ln(\frac{1}{1+e^{-x}}) = \ln(1) - \ln(1+e^{-x}) = 0-\ln(1+e^{-x})=-\ln(1+e^{-x}) = -\text{softplus}(-x)
\end{equation}

### 3.

\begin{equation}
\frac{\partial}{\partial x}\text{sigmoid}(x) = \frac{\partial}{\partial x}\frac{1}{1+e^{-x}} = -(1+e^{-x})^{-2}(-e^{-x}) = \frac{e^{-x}}{(1+e^{-x})^2} = \frac{1}{1+e^{-x}}\frac{e^{-x}}{1+e^{-x}} = \frac{1}{1+e^{-x}}\frac{1-1+e^{-x}}{1+e^{-x}} = \frac{1}{1+e^{-x}}(\frac{1+e^{-x}}{1+e^{-x}} - \frac{1}{1+e^{-x}}) = \frac{1}{1+e^{-x}}(1-\frac{1}{1+e^{-x}}) =\text{sigmoid}(x) (1 - \text{sigmoid}(x))
\end{equation}

### 4.

\begin{equation}
\frac{\partial}{\partial x}(\tanh(x)) = \frac{\partial}{\partial x} (\frac{e^x - e^{-x}}{e^x + e^{-x}}) = \frac{e^x + e^{-x}}{e^x + e^{-x}} - (e^x - e^{-x})(e^x + e^{-x})^{-2}(e^x - e^{-x}) = 1 - (\frac{e^x - e^{-x}}{e^x + e^{-x}})^2 = 1 - \tanh(x)^2
\end{equation}

### 5.

\begin{equation}
\text{sign}(x) = 1_{x>0}(x) - 1_{x<0}(x)
\end{equation}

### 6.

\begin{equation}
\text{abs'}(x) = \text{sign(x)}
\end{equation}

### 7.

\begin{equation}
\text{rect'}(x) = 1_{x>0}(x)
\end{equation}

### 8.

\begin{equation}
\frac{\partial L_2}{\partial x} = \begin{bmatrix}\frac{\partial}{\partial x_1}\\
\frac{\partial}{\partial x_2}\\
\vdots \\
\frac{\partial}{\partial x_d}\end{bmatrix} L_2 = \begin{bmatrix}2x_1\\
2x_2\\
\vdots \\
2x_d\end{bmatrix}
\end{equation}

### 9.

\begin{equation}
\frac{\partial L_1}{\partial x} = \begin{bmatrix}\frac{\partial}{\partial x_1}\\
\frac{\partial}{\partial x_2}\\
\vdots \\
\frac{\partial}{\partial x_d}\end{bmatrix} L_1 = \begin{bmatrix}-1_{x<0}(x) + 1_{x>0}(x)\\
-1_{x<0}(x) + 1_{x>0}(x)\\
\vdots \\
-1_{x<0}(x) + 1_{x>0}(x)\end{bmatrix}
\end{equation}

## Question 2: Gradient computation for parameters optimization in a neural net for multiclass classification

### 1.
Le vecteur $b^{(1)}$ est de dimensions $d_h$.

Le vecteur de préactivation de la couche cachée est donné par

\begin{equation}
h^{(a)}(x) = b^{(1)} + W^{(1)}h^{(0)}(x)
\end{equation}

avec $h^{(0)}(x) = x$.

Pour calculer un élément particulier de rang $j$, on utilise

\begin{equation}
h^{(a)}_j(x) =  b^{(1)}_j + \sum\limits_{i = 1}^d W^{(1)}_{ji}x_i.
\end{equation}

Les éléments du  vecteur de sortie pour la couche cachée, $h^{(s)}(x)$ sont donnés par

\begin{equation}
h^{(s)}_j(x) = \max(0,h^{(a)}_j(x)).
\end{equation}

### 2.

Les dimensions de la matrice $W^{(2)}$ est $(m,d_h)$ et celles du vecteur $b^{(2)}$ sont $(m,1)$. La formule d'activation de la couche de sortie est donnée par

\begin{equation}
o^{(a)}(x) = b^{(2)} + W^{(2)}h^{(s)}(x).
\end{equation}

Chaque élément $o^{(a)}_k(x)$ de ce vecteur est donné par

\begin{equation}
o^{(a)}_k(x) = b^{(2)}_k + \sum\limits_{j = 1}^{d_h} W^{(2)}_{kj}h^{(s)}_j(x).
\end{equation}

### 3.

Les éléments du vecteur de sortie $o^{(s)}_k(x)$ sont donnés par

\begin{equation}
o^{(s)}_k(x) = \text{softmax}(o^{(a)}_k(x)) = \ln(1 + \exp(o^{(a)}_k(x))) = \ln(1 + \exp(b^{(2)}_k + \sum\limits_{j = 1}^{d_h} W^{(2)}_{kj}h^{(s)}_j(x))).
\end{equation}

Les $o^{(s)}_k(x)$ sont tous positifs, car $(\exp(x) > 0 \text{ pour } x \in \rm I\!R)$, donc $1 + \exp(x) > 1$, donc $\ln(1+\exp(x)) > 0$, car $\ln(x) > 0\text{ pour } x > 1$.

???Normalisation???

### 4.

La fonction de perte est donnée par

\begin{equation}
L(x,y) = -\ln(\ln(1+\exp(o^{(a)}(x)\times \text{onehot}_m(y))))
\end{equation}

### 5.

Le risque empirique $\hat{R}(x)$ du dataset $D_n$ est donné par

\begin{equation}
\hat{R}(x) = \sum\limits_{x \in D_n} \sum\limits_{y =1}^m L(x,y).
\end{equation}

L'ensemble $\theta$ des paramètres du système est 

\begin{equation}
\theta = \{W^{(1)}, b^{(1)}, W^{(2)}, b^{(2)}\}.
\end{equation}

$W^{(1)}$ est de dimension $(d_h,d)$, $b^{(1)}$ est de dimension $d_h$, $W^{(2)}$ est de dimension $(m,d_h)$ et $b^{(2)}$ est de dimension $m$. Le nombre de paramètres scalaires total est donc $n_\theta = d_h(d+1) + m(d_h+1)$

Les valeurs de paramètres optimisées seront obtenues par

\begin{equation}
\theta^* = \text{argmin}_{\theta}(-\sum\limits_{x \in D_n} \sum\limits_{y=1}^m \ln(\ln(1+\exp(o^{(a)}_y(x)\times \text{onehot}_m(y)))))
\end{equation}

## 6.

L'équation pour le batch gradient descent est

\begin{equation}
\nabla(\theta) = \frac{1}{n} \sum\limits_{x\in D_n}[\frac{\partial}{\partial \theta}\sum\limits_{y=1}^m -\ln(\ln(1+\exp(o^{(a)}_y(x)\times \text{onehot}_m(y)))) ],\\
\theta \leftarrow \theta - \eta\nabla(\theta).
\end{equation}

## 7.

À voir

## 8.

```python
grad_oa = os
grad_oa[np.argmax(os)] -= 1
```

## 9.

\begin{equation}
\frac{\partial L}{\partial W^{(2)}_{kj}} = \frac{\partial L}{\partial o^{(a)}_{k}} \frac{\partial o^{(a)}_{k}}{\partial W^{(2)}_{kj}} = \frac{\partial L}{\partial o^{(a)}_{k}} h^{(s)}_j\\
\frac{\partial L}{\partial b^{(2)}_{k}} = \frac{\partial L}{\partial o^{(a)}_{k}} \frac{\partial o^{(a)}_{k}}{\partial b^{(2)}_{k}} = \frac{\partial L}{\partial o^{(a)}_{k}}
\end{equation}

## 10.

\begin{equation}
\frac{\partial L}{\partial W^{(2)}}_{m \times d_h} = \frac{\partial L}{\partial o^{a}}_{m \times 1} \cdot [h^{(s)}]^T_{1\times d_h}\\
\frac{\partial L}{\partial b^{(2)}}_{m \times 1} = \frac{\partial L}{\partial o^{(a)}}_{m \times 1}
\end{equation}

```python
grad_b2 = np.copy(grad_oa)
grad_W2 = grad_oa * hs.T
```

## 11.

\begin{equation}
\frac{\partial L}{\partial h^{(s)}_{j}} = \frac{\partial L}{\partial o^{(a)}_{k}} \frac{\partial o^{(a)}_{k}}{\partial h^{(s)}_{j}} = \frac{\partial L}{\partial o^{(a)}_{k}} W^{(2)}_{kj}
\end{equation}

## 12.

\begin{equation}
\frac{\partial L}{\partial h^{(s)}_{j}}_{d_h \times 1} = [W^{(2)}]^T_{d_h \times m} \cdot \frac{\partial L}{\partial o^{(a)}_{k}}_{m \times 1}
\end{equation}

~~~python
grad_hs = W2.T * grad_oa
~~~

## 13.

\begin{equation}
\frac{\partial L}{\partial h^{(a)}_{j}} = \frac{\partial L}{\partial h^{(s)}_{j}} \frac{\partial h^{(s)}_{j}}{\partial h^{(a)}_{j}} = \frac{\partial L}{\partial h^{(s)}_{j}} \cdot 1_{x>0}(h^{(a)}_j)
\end{equation}

## 14.

\begin{equation}
\frac{\partial L}{\partial h^{(a)}_{j}}_{d_h \times 1} = \frac{\partial L}{\partial h^{(s)}_{j}}_{d_h \times 1} \cdot 1_{x>0}(h^{(a)}_j)_{d_h \times 1}
\end{equation}

~~~python
rect = np.zeros(grad_hs.shape)
rect[ha>0] = 1
grad_ha = grad_hs * rect
~~~

## 15.

\begin{equation}
\frac{\partial L}{\partial W^{(1)}_{ji}} = \frac{\partial L}{\partial h^{(a)}_{j}} \frac{\partial h^{(a)}_{j}}{\partial W^{(1)}_{ji}} = \frac{\partial L}{\partial h^{(a)}_{j}} h_i^{(0)}\\
\frac{\partial L}{\partial b^{(1)}_{j}} = \frac{\partial L}{\partial h^{(a)}_{j}}
\end{equation}

## 16.

\begin{equation}
\frac{\partial L}{\partial W^{(1)}}_{d_h \times d} = \frac{\partial L}{\partial h^{(a)}}_{d_h\times 1} \cdot [h^{(0)}]^T_{1\times d}\\
\frac{\partial L}{\partial b^{(1)}}_{d_h\times 1} = \frac{\partial L}{\partial h^{(a)}}_{d_h\times 1}
\end{equation}

~~~python
grad_W1 = grad_ha * h0.T
grad_b1 = np.copy(grad_ha)
~~~

## 17.

\begin{equation}
\frac{\partial L}{\partial x_{i}} = \frac{\partial L}{\partial h^{(a)}_{j}} \frac{\partial h^{(a)}_{j}}{\partial h^{(0)}_i}\frac{\partial h^{(0)}_{i}}{\partial x_i} = \frac{\partial L}{\partial h^{(a)}_{j}} \cdot W^{(1)}_{ji} \cdot 1
\end{equation}

## 18.

L'ajout d'un terme de régularisation change seulement les gradients pour $W^{(1)}$ et $W^{(2)}$. Ils deviendront

\begin{equation}
\frac{\partial L}{\partial W^{(2)}}_{m \times d_h} = \frac{\partial L}{\partial o^{a}}_{m \times 1} \cdot [h^{(s)}]^T_{1\times d_h} + \lambda_{21}(-1_{x<0}(W^{(2)}) + 1_{x>0}(W^{(2)}))_{m\times d_h} + 2\lambda_{22}W^{(2)}_{m\times d_h}\\
\frac{\partial L}{\partial W^{(1)}}_{d_h \times d} = \frac{\partial L}{\partial h^{a}}_{d_h \times 1} \cdot [h^{(0)}]^T_{1\times d} + \lambda_{11}(-1_{x<0}(W^{(1)}) + 1_{x>0}(W^{(1)}))_{d_h\times d} + 2\lambda_{12}W^{(1)}_{d_h\times d}
\end{equation}

~~~python
rect = np.ones(W2.shape)
rect[W2<0] = -1.
grad_W2 = grad_oa * hs.T + lambda21 * rect + 2 * lambda22 * W2
rect = np.ones(W1.shape)
rect[W1<0] = -1.
grad_W1 = grad_ha * h0.T + lambda11 * rect + 2 * lambda12 * W1
~~~

In [2]:
import numpy as np

In [5]:
m = 5
dh = 7

grad_oa= np.ones((m,1))
hs = np.ones((1,dh))
grad_W2 = grad_oa * hs

In [6]:
print(grad_W2)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [13]:
a = np.array([4,3])
b = a * 1
a[1] += 1
print(a)
print(b)

[4 4]
[4 4]


In [22]:
ha = np.array([1, 2, 3, -2, -4, 6])
ha.shape

np.zeros(ha.shape)

array([0., 0., 0., 0., 0., 0.])

In [33]:
np.maximum(ha,np.zeros(ha.shape))

array([1., 2., 3., 0., 0., 6.])

In [35]:
grad = np.zeros(ha.shape)
grad[ha>0] = 1
print(grad)

[1. 1. 1. 0. 0. 1.]


In [42]:
W2 = np.random.rand(4,6)-0.5
print(W2)

[[ 0.39724442 -0.07467383 -0.4837776   0.32199726 -0.31546464  0.24474138]
 [ 0.37338073 -0.05939823 -0.20622889  0.15768532 -0.02983222  0.48093379]
 [ 0.02392249 -0.26874833  0.17679754 -0.2450788  -0.16357716  0.07564577]
 [-0.39319279 -0.48694134  0.08791934  0.37566871 -0.04758637 -0.03888703]]


In [43]:
rect = np.ones(W2.shape)
rect[W2<0] = -1.
print(rect)

[[ 1. -1. -1.  1. -1.  1.]
 [ 1. -1. -1.  1. -1.  1.]
 [ 1. -1.  1. -1. -1.  1.]
 [-1. -1.  1.  1. -1. -1.]]
